{% set name = "bayesfilter" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/bayesfilter-{{ version }}.tar.gz
  sha256: 2fcad9220aaea883879331b3df48ae30aad6f0a825e468aecca3c99bd8e54686

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - bayesfilter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hugohadfield/bayesfilter
  summary: A pure Python/NumPy library for Bayesian filtering and smoothing
  license: MIT
  license_file: licence.txt

extra:
  recipe-maintainers:
    - thewchan
