schema_version: 1

context:
  name: bayesfilter
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/bayesfilter-${{ version }}.tar.gz
  sha256: f852996421728aad38085a305e0a76bc34efdfe5c2faad1fd59882dbcab3020c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy >=1.21.3

tests:
  - python:
      imports:
        - bayesfilter
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A pure Python/NumPy library for Bayesian filtering and smoothing
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/hugohadfield/bayesfilter

extra:
  recipe-maintainers:
    - thewchan
